stages:
  - build
  - deploy

build:
  image: docker:latest
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  only:
    - tags

deploy:
  image: docker
  stage: deploy
  before_script:
    - "which ssh-agent || ( apk update && apk add openssh-client )"
    - eval $(ssh-agent -s)
    - echo "$PRIVATE_KEY_PROD" | ssh-add -
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

  script:
    - ssh apps@$IP "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
    - ssh apps@$IP "docker service update ta_image-proxy --image $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG --update-failure-action rollback --with-registry-auth"
    - ssh apps@$IP "docker system prune -af"
  tags: [ssh]
  when: manual
  only:
    - tags
